### ISSUE TITLE
[community] remap antrea.io/live & antrea.io/notes

### ISSUE THREAD

**Issue by jayunit100** [antrea-io/website#13]
**Describe the bug**

antrea.io/live points to a google doc, but @yashbhutwala had a great idea to use a hackmd.io file.

- please remap `antrea.io/notes` to `https://hackmd.io/@jayunit100/antrea-LIVE/edit`
- please remap `antrea.io/live` to
`https://github.com/jayunit100/k8sprototypes/blob/master/antrea-LIVE/README.md`

(or if theres a way i can PR / edit this just let me know ill do it)

thanks !

**Expected**

Antrea live links are easy to read and access/interact with.

**Comment by antoninbas** [comment]
Fixed by https://github.com/antrea-io/website/pull/14
